from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_redirect, name='home_redirect'),  # root path
    path('home', views.home, name='home' ),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('password_reset/', views.password_reset, name='password_reset'),
    # path('guest_booking/', views.guest_booking, name='guest_booking'),
    path('logout/', views.logout_view, name='logout'),

    # Dashboards
    # path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('doctor_dashboard/', views.doctor_dashboard, name='doctor_dashboard'),
    path('patient_dashboard/', views.patient_dashboard, name='patient_dashboard'),

    # Doctor URLs
    path('prescription_list/', views.prescription_list, name='prescription_list'),
    path('delete_prescription/<int:prescription_id>/', views.delete_prescription, name='delete_prescription'),
    path('doctor_appointments/', views.doctor_appointments, name='doctor_appointments'),
    path('doctor_calendar/', views.doctor_calendar, name='doctor_calendar'),
    path('doctor_schedule/', views.doctor_schedule, name='doctor_schedule'),
    path('doctor_create_prescription/', views.doctor_create_prescription, name='doctor_create_prescription'),
    path('doctor_patient_record/', views.doctor_patient_record, name='doctor_patient_record'),
    path('doctor/patients/<int:patient_id>/records/add/', views.add_medical_record, name='add_medical_record'), 
    path('doctor/records/<int:record_id>/delete/', views.delete_medical_record, name='delete_medical_record'),
    path('doctor_patients/', views.doctor_patient_list, name='doctor_patient_list'),
    path('doctor_patient_record/<int:patient_id>/', views.doctor_patient_record, name='doctor_patient_record'),
    path('availability_update', views.availability_update, name='availability_update'),
    path('appointment_calendar_view', views.appointment_calendar_view, name='appointment_calendar_view'),
    path('appointment_create', views.appointment_create, name='appointment_create'),
    path('appointment_detail_ajax/<int:appointment_id>/', views.appointment_detail_ajax, name='appointment_detail_ajax'),

    # Patient URLs
    path('find_doctor/', views.find_doctor, name='find_doctor'),
    path("doctor_detail/<int:doctor_id>/", views.doctor_detail, name="doctor_detail"),
    path('patient_prescriptions_list/', views.patient_prescriptions_list, name='patient_prescriptions_list'),
    path('medical_records/', views.medical_records, name='medical_records'),
    path('appointment_history/', views.appointment_history, name='appointment_history'),
    path('book_appointment/', views.book_appointment, name='book_appointment'),
    path('patient_details/<int:patient_id>/', views.patient_details, name='patient_details'),
    path('download_prescription/<int:id>/', views.download_prescription, name='download_prescription'),
    path('share_prescription/<int:id>/', views.share_prescription, name='share_prescription'),

    # Common
    path('appointment_update_status/<int:appointment_id>/', views.appointment_update_status, name='appointment_update_status'),
    path('upload_medical_record/', views.upload_medical_record, name='upload_medical_record'),
    path('create_prescription/<int:appointment_id>/', views.create_prescription, name='create_prescription'),
    path('edit_prescription/<int:prescription_id>/', views.edit_prescription, name='edit_prescription'),
    path('user_management/', views.user_management, name='user_management'),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path("appointment_management/", views.appointment_management, name="appointment_management"),
    path("reports_dashboard/", views.reports_dashboard, name="reports_dashboard"),
    path("announcements/", views.announcements, name="announcements"),
    path("create_announcements/", views.create_announcements, name="create_announcements"),
    path('edit_announcement/<int:pk>/', views.edit_announcement, name='edit_announcement'),
    path('toggle_announcement/<int:pk>/', views.toggle_announcement, name='toggle_announcement'),
    path('delete_announcement/<int:pk>/', views.delete_announcement, name='delete_announcement'),
    path("add_user/", views.add_user, name="add_user"),
    path("view_user/<int:id>/", views.view_user, name="view_user"),
    path("edit_user/<int:user_id>/", views.edit_user, name="edit_user"),
    path("toggle_user_status/<int:id>/", views.toggle_user_status, name="toggle_user_status"),
    path("export_appointments/", views.export_appointments, name="export_appointments"),
    path("appointment_analytics/", views.appointment_analytics, name="appointment_analytics"),
    path("view_appointment/<int:appointment_id>/", views.view_appointment, name="view_appointment"),
    path("export_users_csv/", views.export_users_csv, name="export_users_csv"),
    path("reports_analytics/", views.reports_analytics, name="reports_analytics"),
    path("generate_report/", views.generate_report, name="generate_report"),
    path('view_report<int:report_id>/', views.view_report, name='view_report'),
    path("activity_logs/", views.activity_logs, name="activity_logs"),
    path('activity_log_details/<int:log_id>/', views.activity_log_details, name='activity_log_details'),
    path('activity-logs/export/', views.export_activity_logs, name='export_activity_logs'),
    path('clear_activity_logs/', views.clear_activity_logs, name='clear_activity_logs'),
    path("system_settings/", views.system_settings, name="system_settings"),
    path("backup_management/", views.backup_management, name="backup_management"),
    path("maintenance_tools/", views.maintenance_tools, name="maintenance_tools"),
    path("system_status/", views.system_status, name="system_status"),
]
