# Generated by Django 5.2.4 on 2025-08-08 08:51

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', 'time']},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='appointment',
            name='other_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('CHECKUP', 'Routine Checkup'), ('CONSULT', 'General Consultation'), ('FEVER', 'Fever/Infection'), ('INJURY', 'Injury Treatment')], default='CONSULT', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_time_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PK'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Suggested next visit', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_digital_signature',
            field=models.BooleanField(default=False, help_text='True if doctor digitally signed this prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PK'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='roll',
            field=models.CharField(choices=[('admin', 'Admin'), ('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(upload_to='medical_records/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='systemreport',
            name='file',
            field=models.FileField(upload_to='system_reports'),
        ),
        migrations.AlterField(
            model_name='systemreport',
            name='report_type',
            field=models.CharField(choices=[('users', 'User Statistics'), ('appointments', 'Appointment Reports'), ('prescriptions', 'Prescription Analysis')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['specialization'], name='MediTrackAp_special_019b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['city'], name='MediTrackAp_city_76058a_idx'),
        ),
    ]
