# Generated by Django 5.2.4 on 2025-08-11 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0003_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediTrackApp.appointment'),
        ),
    ]
