# Generated by Django 5.2.4 on 2025-08-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0005_rename_roll_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
