# Generated by Django 5.2.4 on 2025-08-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0006_alter_doctorprofile_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_time_slots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
