# Generated by Django 5.2.4 on 2025-08-17 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0008_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_type',
        ),
    ]
