# Generated by Django 5.2.4 on 2025-08-18 07:14

import MediTrackApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0010_activitylog_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[MediTrackApp.models.validate_file_extension]),
        ),
    ]
