# Generated by Django 5.2.4 on 2025-08-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0011_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemreport',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], default='csv', max_length=10),
        ),
        migrations.AddField(
            model_name='systemreport',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='systemreport',
            name='report_type',
            field=models.CharField(choices=[('users', 'User Statistics'), ('appointments', 'Appointment Reports'), ('prescriptions', 'Prescription Analysis'), ('financial', 'Financial Report')], max_length=50),
        ),
    ]
