# Generated by Django 5.2.4 on 2025-08-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0012_systemreport_format_systemreport_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemreport',
            old_name='created_at',
            new_name='generated_at',
        ),
    ]
