# Generated by Django 5.2.4 on 2025-08-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0014_announcement_end_date_announcement_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Record Created'), ('update', 'Record Updated'), ('delete', 'Record Deleted'), ('status_change', 'Status Changed'), ('password_change', 'Password Changed'), ('profile_update', 'Profile Updated'), ('appointment_booked', 'Appointment Booked'), ('appointment_updated', 'Appointment Updated'), ('prescription_created', 'Prescription Created'), ('report_generated', 'Report Generated'), ('announcement_created', 'Announcement Created')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
