# Generated by Django 5.2.4 on 2025-08-20 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0015_activitylog_user_agent_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('setting_type', models.CharField(choices=[('boolean', 'Boolean'), ('string', 'String'), ('integer', 'Integer'), ('text', 'Text'), ('json', 'JSON')], max_length=10)),
                ('category', models.CharField(choices=[('general', 'General'), ('security', 'Security'), ('appointment', 'Appointment'), ('notification', 'Notification'), ('backup', 'Backup'), ('maintenance', 'Maintenance')], default='general', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('system', 'System Maintenance'), ('database', 'Database Maintenance'), ('backup', 'Backup Operation'), ('update', 'System Update'), ('cleanup', 'Cleanup Operation')], max_length=20)),
                ('description', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], default='pending', max_length=10)),
                ('affected_records', models.IntegerField(default=0)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
