# Generated by Django 5.2.4 on 2025-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediTrackApp', '0016_systemsetting_backuplog_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
    ]
